apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: izzatzr/phpdev:v0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: web
  type: ClusterIP
